### ISSUE TITLE
JSP UI and H2 console don't run

### ISSUE THREAD

**Issue by a7l97nn** [aleksey-lukyanets/market#59]
Привет!

Попытался запустить Ваш проект на окружении:
 * Windows 10
 * IntelliJ IDEA Community 2020.2
 * OpenJDK 11 2018-09-25

Но при открытии localhost:8080 в браузере (Chrome 85.0.4183.102 (Официальная сборка), (64 бит)), отображается "Whitelabel Error Page" с ошибкой 404.
В этот момент в консоли появляется предупреждение:

![image](https://user-images.githubusercontent.com/9952799/93086079-3bb25f80-f69f-11ea-8e48-5843d73a119c.png)

Так же, при попытке открыть консоль H2, то получаю следующее:

![image](https://user-images.githubusercontent.com/9952799/93086152-5a185b00-f69f-11ea-99fd-548e784cb7cf.png)

If you need to english comments, just let me know.

**Comment by aleksey-lukyanets** [comment]
Привет!

Спасибо за Ваше указание и внимание к моему проекту. Теперь должно работать.
