### ISSUE TITLE
Running applications from the root directory

### ISSUE THREAD

**Issue by BaiGeiQiShi** [aleksey-lukyanets/market#77]
Dear aleksey-lukyanets，

Thanks for making this market API!

I'm interested in using this API for a test. I followed the instructions in README.md to have the API installed. But I didn't know how to run this project. I have tried the command: `mvn spring-boot:run`, but it didn't work.
![image](https://user-images.githubusercontent.com/67951843/147900528-88319c97-df3f-4e5f-93f9-dc77741d645f.png)
I know this is a multi module project, but I don't know how to exec this project. Could you help me? Thanks in advance!

**Comment by aleksey-lukyanets** [comment]
Hello, BaiGeiQiShi,

thank you for your attention to my project.

This project contains two executable modules each of that could be run separately. When running from the parent directory of the project you have to specify a module you would like run, e.g. this way:

`mvn spring-boot:run -pl <module-name, e.g. market-web>`

I updated the README to make things more explicit.

**Comment by aleksey-lukyanets** [comment]
You are welcome.
It seems in Readme there is a misprint about Swagger UI port, it shall be same to the one of REST application, by default: 8081.
Please try `localhost:8081/swagger-ui/#/` after running `market-rest`.

**Comment by BaiGeiQiShi** [comment]
Oh, I should have thought the port was wrong.
It now works for me. I can't express how grateful I am. Thank you for your guidance. 
Wish you a good life!

**Comment by aleksey-lukyanets** [comment]
You are welcome! Feel free asking if you will have further questions.
Thank you for the kind words and have a nice day.

**Comment by BaiGeiQiShi** [comment]
Thanks a lot!
